swagger: '2.0'
paths:
  /{api:v1}: &default_project_paths_v1
    swagger: '2.0'
    # swagger options, overriding the shared ones from the merged specs (?)
    info:
      version: 1.0.0-beta
      title: Wikimedia REST API
      description: >
          This API aims to provide coherent and low-latency access to
          Wikimedia content and services. It is currently in beta testing, so
          things aren't completely locked down yet. Each entry point has
          explicit stability markers to inform you about development status
          and change policy, according to [our API version
          policy](https://www.mediawiki.org/wiki/API_versioning).

          ### High-volume access
            - Don't perform more than 500 requests/s to this API.
            - Set a unique `User-Agent` header that allows us to contact you
              quickly. Email addresses or URLs of contact pages work well.

      termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
      contact:
        name: the Wikimedia Services team
        url: http://mediawiki.org/wiki/RESTBase
      license:
        name: Apache2
        url: http://www.apache.org/licenses/LICENSE-2.0
      x-is-api-root: true

    securityDefinitions: &wp/content-security/1.0.0
      mediawiki_auth:
        description: Checks permissions using MW api
        type: apiKey
        in: header
        name: cookie
        x-internal-request-whitelist:
          - /http:\/\/[a-zA-Z0-9\.]+\/w\/api\.php/
          - http://parsoid-lb.eqiad.wikimedia.org
      header_match:
        description: Checks client ip against one of the predefined whitelists
        x-error-message: This client is not allowed to use the endpoint
        x-whitelists:
          internal:
            - /^(?:::ffff:)?(?:10|127)\./
        x-is-api: true
    # Override the base path for host-based (proxied) requests. In our case,
    # we proxy https://{domain}/api/rest_v1/ to the API.
    x-host-basePath: /api/rest_v1

    x-modules:
      /media:
        - path: v1/mathoid.yaml
      /metrics:
        - path: v1/pageviews.yaml

  /{api:sys}:
    x-modules:
      /table:
        - type: npm
          name: restbase-mod-table-cassandra
          options:
            conf: '{{options.cassandra}}'
      /key_value:
        - path: sys/key_value.js
      /key_rev_value:
        - path: sys/key_rev_value.js
      /page_revisions:
        - path: sys/page_revisions.js
      /post_data: &sys_post_data
        - path: sys/post_data.js
      /media:
        - path: sys/mathoid.yaml
          options: '{{options.mathoid}}'
      /pageviews:
        - path: sys/pageviews.js
