# MobileApps page-manipulation service

swagger: 2.0
paths:
  /mobile-sections/{title}:
    get:
      tags:
        - Mobile
      description: |
        Retrieve the latest HTML for a page title optimised for viewing with
        native mobile applications. Note that the output is split by sections.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/v1/handling/rev/mobile-sections/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: true
      x-amples:
        - title: Get MobileApps Foobar page
          request:
            params:
              domain: en.wikipedia.org
              title: Foobar
          response:
            status: 200
            headers:
              content-type: /application\/json/
            body:
              lead: /.+/
              remaining: /.+/

  /mobile-sections-lead/{title}:
    get:
      tags:
        - Mobile
      description: |
        Retrieve the lead section of the latest HTML for a page title optimised
        for viewing with native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/v1/handling/rev/mobile-sections-lead/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false

  /mobile-sections-remaining/{title}:
    get:
      tags:
        - Mobile
      description: |
        Retrieve the remainder of the latest HTML (without the lead section) for
        a page title optimised for viewing with native mobile applications,
        provided as a JSON object containing the sections.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/v1/handling/rev/mobile-sections-remaining/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false

  /mobile-text/{title}:
    get:
      tags:
        - Mobile
      description: |
        Retrieve the *lite* version of the latest HTML for a page title optimised for viewing with
        native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The JSON comprising the HTML and various page attributes for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: '{+$$.options.host}/{domain}/v1/page/mobile-text/{title}'
              headers:
                cache-control: '{cache-control}'
      x-monitor: false
