language: node_js
node_js:
    # Production runs 0.10.29
    - "0.10.29"
    - "0.10"
    - "0.12"
    - "4.2"

sudo: false

services:
    - cassandra

notifications:
  email:
    - services@wikimedia.org

script: sh test/utils/run_tests.sh coverage all && (npm run-script coveralls || exit 0)
