language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4.2"

sudo: false

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-services"
    on_success: change
    on_failure: always

before_install:
  - wget https://archive.apache.org/dist/cassandra/2.1.12/apache-cassandra-2.1.12-bin.tar.gz
  - tar -xzf apache-cassandra-2.1.12-bin.tar.gz
  - sh apache-cassandra-2.1.12/bin/cassandra > /dev/null

script: sh test/utils/run_tests.sh coverage all && (npm run-script coveralls || exit 0)
