language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "4.2"

sudo: false

services:
    - cassandra

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-services"
    on_success: change
    on_failure: always

script: sh test/utils/run_tests.sh coverage all && (npm run-script coveralls || exit 0)
