# RESTBase test config, used in integration tests.

# First, we define some project templates. These are referenced / shared
# between domains in the root_spec further down.
default_project: &default_project
  swagger: '2.0'
  paths:
    /{api:v1}: &default_project_paths_v1
      # Spec root, resulting in an aggregated public spec & docs.
      swagger: '2.0'
      info:
        version: 1.0.0-beta
        title: Wikimedia REST API
        description: >
            This API aims to provide coherent and low-latency access to
            Wikimedia content and services. It is currently in beta testing, so
            things aren't completely locked down yet. Each entry point has
            explicit stability markers to inform you about development status
            and change policy, according to [our API version
            policy](https://www.mediawiki.org/wiki/API_versioning).

            ### High-volume access
              - Don't perform more than 500 requests/s to this API.
              - Set a unique `User-Agent` header that allows us to contact you
                quickly. Email addresses or URLs of contact pages work well.

        termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
        contact:
          name: the Wikimedia Services team
          url: http://mediawiki.org/wiki/RESTBase
        license:
          name: Apache2
          url: http://www.apache.org/licenses/LICENSE-2.0
        x-is-api-root: true

      securityDefinitions:
        mediawiki_auth:
          description: Checks permissions using MW api
          type: apiKey
          in: header
          name: cookie
          x-internal-request-whitelist:
            - https://en.wikipedia.org/w/api.php
            - https://fr.wikipedia.org/w/api.php
            - http://en.wikipedia.beta.wmflabs.org/w/api.php
            # Left as a regex for test purpose
            - /http:\/\/parsoid\-beta\.wmflabs\.org/
        header_match:
          description: Checks client ip against one of the predefined whitelists
          x-error-message: This client is not allowed to use the endpoint
          x-whitelists:
            internal:
              - /^(?:::ffff:)?(?:10|127)\./
          x-is-api: true

      x-modules: &default_project_paths_v1_modules
        /: 
          # The main content module, defining page/* and transform entry
          # points.
          - path: v1/content.yaml
          - path: test/test_module.yaml
        /page:
          - path: v1/mobileapps.yaml
            options:
              host: http://appservice.wmflabs.org
          - path: v1/graphoid.yaml
            options:
              host: http://graphoid.wikimedia.org
          - path: v1/summary.js
            options:
              response_cache-control: 'max-age: 3600, s-maxage: 3600'
        /media:
          - path: v1/mathoid.yaml
            options:
              host: http://mathoid-tester.wmflabs.org

    /{api:sys}: &default_project_paths_sys
      x-modules: &default_project_paths_sys_modules
        /table: &sys_table
          - type: npm
            name: restbase-mod-table-cassandra
            # See: 
            # https://github.com/wikimedia/restbase-mod-table-cassandra/blob/master/Readme.md#configuration
            options:
              conf:
                dbname: test.db.sqlite3 # ignored in cassandra, but useful in SQLite testing
                hosts: [localhost]
                keyspace: system
                username: cassandra
                password: cassandra
                defaultConsistency: one # or 'one' for single-node testing
                storage_groups:
                  - name: test.group.local
                    domains: /./
        /key_value: &sys_key_value
          - path: sys/key_value.js
        /key_rev_value:
          - path: sys/key_rev_value.js
        /page_revisions:
          - path: sys/page_revisions.js
        /post_data: &sys_post_data
          - path: sys/post_data.js
        /action:
          - path: sys/action.js
            options:
              apiUriTemplate: "{{'https://{domain}/w/api.php'}}"
        /page_save:
          - path: sys/page_save.js
        /parsoid:
          - path: sys/parsoid.js
            options:
              parsoidHost: http://parsoid-beta.wmflabs.org
              # For local testing, use:
              # parsoidHost: http://localhost:8000
        /mobileapps:
          - path: sys/mobileapps.yaml
            options:
              host: http://appservice.wmflabs.org

labs_project: &labs_project
  swagger: '2.0'
  paths:
    /{api:v1}: *default_project_paths_v1
    /{api:sys}:
      x-modules:
        <<: *default_project_paths_sys_modules
        # Override the action API config to use http
        /action:
          - path: sys/action.js
            options:
              apiUriTemplate: "{{'http://{domain}/w/api.php'}}"

wikimedia.org: &wikimedia.org
  swagger: '2.0'
  paths:
    /{api:v1}:
      <<: *default_project_paths_v1
      # Override x-modules
      x-modules:
        /:
          - path: test/test_module.yaml
        /media:
          - path: v1/mathoid.yaml
            options:
              host: http://mathoid-tester.wmflabs.org
        /metrics:
          - path: v1/pageviews.yaml

    /{api:sys}:
      x-modules:
        /table: *sys_table
        /key_value: *sys_key_value
        /post_data: *sys_post_data
        /pageviews:
          - path: sys/pageviews.js

private_project: &private_project
  swagger: '2.0'
  paths:
    /{api:v1}:
      # Merge in the default project v1 paths
      <<: *default_project_paths_v1
      # Tighten down security for everything below /v1/.
      security:
        - mediawiki_auth:
          - read
    /{api:sys}: *default_project_paths_sys

# Hacky way to parametrize RESTBase tests. TODO: Move to config?
test:
  content_types:
    html: text/html; charset=utf-8; profile="mediawiki.org/specs/html/1.1.0"
    data-parsoid: application/json; charset=utf-8; profile="mediawiki.org/specs/data-parsoid/0.0.1"
    wikitext: text/plain; charset=utf-8; profile="mediawiki.org/specs/wikitext/1.0.0"


# The root of the spec tree. Domains tend to share specs by referencing them
# using YAML references.
spec_root: &spec_root
  title: "The RESTBase root"
  # Some more general RESTBase info
  paths:
    /{domain:en.wikipedia.org}: *default_project
    /{domain:test.wikipedia.org}: *default_project
    /{domain:test2.wikipedia.org}: *default_project

    # labs, used for most tests
    /{domain:en.wikipedia.beta.wmflabs.org}: *labs_project

    # For security testing we rely on mocks, so it's OK to use French wiki.
    /{domain:fr.wikipedia.org}: *private_project

    # global domain
    /{domain:wikimedia.org}: *wikimedia.org

# Finally, a standard service-runner config.
info:
  name: restbase

services:
  - name: restbase
    module: ./lib/server
    conf: 
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 1
      user_agent: RESTBase-testsuite

logging:
  name: restbase
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  #type: txstatsd
  #host: localhost
  #port: 8125
