# RESTBase wikimedia example config

# Load some project templates. These are referenced / shared between domains
# in the root_spec further down.
default_project: &default_project
  x-modules:
    /:
      - path: projects/wmf_default.yaml
        options: &default_options
          table:
            hosts: [localhost]
            keyspace: system
            username: cassandra
            password: cassandra
            defaultConsistency: one # or 'localQuorum' for production
            storage_groups:
              - name: default.group.local
                domains: /./
          parsoid:
            host: http://parsoid-lb.eqiad.wikimedia.org
          action:
            apiUriTemplate: "{{'https://{domain}/w/api.php'}}"
          graphoid:
            host: http://graphoid.wikimedia.org
          mathoid:
            host: http://mathoid-tester.wmflabs.org
          mobileapps:
            host: http://appservice.wmflabs.org

# A different project template, sharing configuration options.
wikimedia.org: &wikimedia.org
  x-modules:
    /:
      - path: projects/wikimedia.org.yaml
        options: *default_options


# The root of the spec tree. Domains tend to share specs by referencing them
# using YAML references.
spec_root: &spec_root
  title: "The RESTBase root"
  paths:
    /{domain:en.wikipedia.org}: *default_project

    # global domain
    /{domain:wikimedia.org}: *wikimedia.org

# Finally, a standard service-runner config.
info:
  name: restbase

services:
  - name: restbase
    module: ./lib/server
    conf: 
      port: 7231
      spec: *spec_root
      salt: secret
      default_page_size: 125
      user_agent: RESTBase

logging:
  name: restbase
  level: info
  #streams:
  #- type: gelf
  #  host: <%= @logstash_host %>
  #  port: <%= @logstash_port %>

metrics:
  #type: txstatsd
  #host: localhost
  #port: 8125
