swagger: '2.0'
info:
  version: '1.0.0'
  title: RESTBase key-value module
  description: Revisioned blob storage with HTTP interface, backed by table storage
paths:
  /key_value/{bucket}:
    get:
      operationId: getBucketInfo
    put:
      operationId: createBucket

  /key_value/{bucket}/:
    get:
      operationId: listBucket

  /key_value/{bucket}/{key}/:
    get:
      operationId: listRevisions

  /key_value/{bucket}/{key}{/tid}:
    get:
      operationId: getRevision
    put:
      operationId: putRevision
