swagger: '2.0'
info:
  version: '1.0.0'
  title: RESTBase post data storage module
  description: Revisioned post data storage with HTTP interface, backed by table storage
paths:
  /post_data/{bucket}:
    get:
      operationId: getBucketInfo
    put:
      operationId: createBucket

  /post_data/{bucket}/:
    get:
      operationId: listBucket

  /post_data/{bucket}/{key}{/tid}:
    get:
      operationId: getRevision

  /post_data/{bucket}/:
    put:
      operationId: putRevision
