# MobileApps page-manipulation service

swagger: 2.0
x-default-params:
  domain: en.wikipedia.org
paths:
  /{module:page}/mobile-html/{title}:
    get:
      tags:
        - Page content
        - Mobile
      description: >
        Retrieve the latest HTML for a page title optimised for viewing with
        native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - text/html
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/html/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false

  /{module:page}/mobile-html-sections/{title}:
    get:
      tags:
        - Page content
        - Mobile
      description: >
        Retrieve the latest HTML for a page title optimised for viewing with
        native mobile applications. Note that the output is split by sections.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/sections/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false
      x-amples:
        - title: Get MobileApps Foobar page
          request:
            params:
              domain: en.wikipedia.org
              title: Foobar
          response:
            status: 200
            headers:
              content-type: /aplication\/json/

  /{module:page}/mobile-html-sections-lead/{title}:
    get:
      tags:
        - Page content
        - Mobile
      description: >
        Retrieve the lead section of the latest HTML for a page title optimised
        for viewing with native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/sections-lead/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false

  /{module:page}/mobile-html-sections-remaining/{title}:
    get:
      tags:
        - Page content
        - Mobile
      description: >
        Retrieve the remainder of the latest HTML (without the lead section) for
        a page title optimised for viewing with native mobile applications,
        provided as a JSON object containing the sections.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/sections-remaining/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false

  /{module:page}/mobile-text/{title}:
    get:
      tags:
        - Page content
        - Mobile
      description: >
        Retrieve the *lite* version of the latest HTML for a page title optimised for viewing with
        native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The JSON comprising the HTML and various page attributes for the given page title.
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - get_from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/text/{title}
              headers:
                cache-control: '{cache-control}'
      x-monitor: false
